version: "3.8"

services:

    nginx:
        image: nginx:stable-alpine
        container_name: nginx_app_container
        ports:
            - "8080:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./project:/var/www/project
        depends_on:
            - php74
            - postgres
        networks:
            - sf5-dev

    php74:
        build: ./php
        container_name: php74_app_container
        ports:
            - "9000:9000"
        volumes:
            - ./project:/var/www/project
        networks:
            - sf5-dev

    postgres:
        image: postgres:13-alpine
        container_name: postgres_app_container
        environment:
            POSTGRES_PASSWORD: symfony
            POSTGRES_USER: symfony
            POSTGRES_DB: symfony
        ports:
            - "5432:5432"
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - sf5-dev

    adminer:
        image: adminer
        container_name: adminer_app_container
        environment:
            ADMINER_DESIGN: pepa-linha
            ADMINER_DEFAULT_SERVER: postgres
        ports:
            - "8888:8080"
        networks:
            - sf5-dev

    mailhog:
        image: mailhog/mailhog
        container_name: mailhog_app_container
        ports:
            - "1080:8025"
        networks:
            - sf5-dev

    redis:
        image: redis:6-alpine
        container_name: redis_app_container
        ports:
            - "6379:6379"
        networks:
            - sf5-dev

    redis-gui:
        image: rediscommander/redis-commander
        container_name: redis-gui_app_container
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - "8081:8081"
        networks:
            - sf5-dev

    node:
        image: node:latest
        container_name: node_app_container
        volumes:
            - ./project:/var/www/project
        working_dir: /var/www/project
        user: '1000:1000'
        ports:
            - "3000:3000"
        networks:
            - sf5-dev


networks:
    sf5-dev:

volumes:
    db-data:
        driver: local
