version: "3.8"

services: 

    portainer-ce:
        image: portainer/portainer-ce
        container_name: portainer-ce
        ports: 
            - "7001:9000"
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always
        networks: 
            - dev

networks: 
    dev:
